// Code generated by MockGen. DO NOT EDIT.
// Source: infra.go

// Package mock_infra is a generated GoMock package.
package mock_infra

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockurlRepo is a mock of urlRepo interface.
type MockurlRepo struct {
	ctrl     *gomock.Controller
	recorder *MockurlRepoMockRecorder
}

// MockurlRepoMockRecorder is the mock recorder for MockurlRepo.
type MockurlRepoMockRecorder struct {
	mock *MockurlRepo
}

// NewMockurlRepo creates a new mock instance.
func NewMockurlRepo(ctrl *gomock.Controller) *MockurlRepo {
	mock := &MockurlRepo{ctrl: ctrl}
	mock.recorder = &MockurlRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockurlRepo) EXPECT() *MockurlRepoMockRecorder {
	return m.recorder
}

// Ping mocks base method.
func (m *MockurlRepo) Ping(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Ping", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Ping indicates an expected call of Ping.
func (mr *MockurlRepoMockRecorder) Ping(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Ping", reflect.TypeOf((*MockurlRepo)(nil).Ping), ctx)
}
