// Code generated by MockGen. DO NOT EDIT.
// Source: infra.go

// Package mock_infra is a generated GoMock package.
package mock_infra

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockurlsRepository is a mock of urlsRepository interface.
type MockurlsRepository struct {
	ctrl     *gomock.Controller
	recorder *MockurlsRepositoryMockRecorder
}

// MockurlsRepositoryMockRecorder is the mock recorder for MockurlsRepository.
type MockurlsRepositoryMockRecorder struct {
	mock *MockurlsRepository
}

// NewMockurlsRepository creates a new mock instance.
func NewMockurlsRepository(ctrl *gomock.Controller) *MockurlsRepository {
	mock := &MockurlsRepository{ctrl: ctrl}
	mock.recorder = &MockurlsRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockurlsRepository) EXPECT() *MockurlsRepositoryMockRecorder {
	return m.recorder
}

// Ping mocks base method.
func (m *MockurlsRepository) Ping(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Ping", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Ping indicates an expected call of Ping.
func (mr *MockurlsRepositoryMockRecorder) Ping(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Ping", reflect.TypeOf((*MockurlsRepository)(nil).Ping), ctx)
}
