// Code generated by MockGen. DO NOT EDIT.
// Source: urls.go

// Package mock_urls is a generated GoMock package.
package mock_urls

import (
	context "context"
	reflect "reflect"

	models "github.com/bgoldovsky/shortener/internal/app/models"
	gomock "github.com/golang/mock/gomock"
)

// MockurlsRepository is a mock of urlsRepository interface.
type MockurlsRepository struct {
	ctrl     *gomock.Controller
	recorder *MockurlsRepositoryMockRecorder
}

// MockurlsRepositoryMockRecorder is the mock recorder for MockurlsRepository.
type MockurlsRepositoryMockRecorder struct {
	mock *MockurlsRepository
}

// NewMockurlsRepository creates a new mock instance.
func NewMockurlsRepository(ctrl *gomock.Controller) *MockurlsRepository {
	mock := &MockurlsRepository{ctrl: ctrl}
	mock.recorder = &MockurlsRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockurlsRepository) EXPECT() *MockurlsRepositoryMockRecorder {
	return m.recorder
}

// Add mocks base method.
func (m *MockurlsRepository) Add(ctx context.Context, urlID, url, userID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Add", ctx, urlID, url, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Add indicates an expected call of Add.
func (mr *MockurlsRepositoryMockRecorder) Add(ctx, urlID, url, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Add", reflect.TypeOf((*MockurlsRepository)(nil).Add), ctx, urlID, url, userID)
}

// AddBatch mocks base method.
func (m *MockurlsRepository) AddBatch(ctx context.Context, urls []models.URL, userID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddBatch", ctx, urls, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddBatch indicates an expected call of AddBatch.
func (mr *MockurlsRepositoryMockRecorder) AddBatch(ctx, urls, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddBatch", reflect.TypeOf((*MockurlsRepository)(nil).AddBatch), ctx, urls, userID)
}

// Get mocks base method.
func (m *MockurlsRepository) Get(ctx context.Context, urlID string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, urlID)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockurlsRepositoryMockRecorder) Get(ctx, urlID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockurlsRepository)(nil).Get), ctx, urlID)
}

// GetList mocks base method.
func (m *MockurlsRepository) GetList(ctx context.Context, userID string) ([]models.URL, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetList", ctx, userID)
	ret0, _ := ret[0].([]models.URL)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetList indicates an expected call of GetList.
func (mr *MockurlsRepositoryMockRecorder) GetList(ctx, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetList", reflect.TypeOf((*MockurlsRepository)(nil).GetList), ctx, userID)
}

// Mockgenerator is a mock of generator interface.
type Mockgenerator struct {
	ctrl     *gomock.Controller
	recorder *MockgeneratorMockRecorder
}

// MockgeneratorMockRecorder is the mock recorder for Mockgenerator.
type MockgeneratorMockRecorder struct {
	mock *Mockgenerator
}

// NewMockgenerator creates a new mock instance.
func NewMockgenerator(ctrl *gomock.Controller) *Mockgenerator {
	mock := &Mockgenerator{ctrl: ctrl}
	mock.recorder = &MockgeneratorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *Mockgenerator) EXPECT() *MockgeneratorMockRecorder {
	return m.recorder
}

// RandomString mocks base method.
func (m *Mockgenerator) RandomString(n int64) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RandomString", n)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RandomString indicates an expected call of RandomString.
func (mr *MockgeneratorMockRecorder) RandomString(n interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RandomString", reflect.TypeOf((*Mockgenerator)(nil).RandomString), n)
}
